# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousFamille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sousfam', models.CharField(max_length=100)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.Famille')),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='sousfam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.SousFamille'),
        ),
    ]
