# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_auto_20170315_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SousComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souscomp', models.CharField(max_length=100)),
                ('composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.Composition')),
            ],
        ),
        migrations.RemoveField(
            model_name='sousfamille',
            name='famille',
        ),
        migrations.RemoveField(
            model_name='famille',
            name='type',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='famille',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='sousfam',
        ),
        migrations.DeleteModel(
            name='SousFamille',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='composition',
            name='famille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.Famille'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.Composition'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='souscomp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.SousComposition'),
        ),
    ]
