# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0003_auto_20170315_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.Composition'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='souscomp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.SousComposition'),
        ),
    ]
