# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0004_auto_20170315_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='presentation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='forme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
