# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0005_auto_20170315_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meds.Famille'),
        ),
    ]
